exclude: migrations
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: CHANGELOG.md
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        types: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        types: [python]
        args: [--config=.flake8]
  - repo: https://github.com/dhruvmanila/remove-print-statements
    rev: "v0.4.0"
    hooks:
      - id: remove-print-statements
        args: ["--verbose"]
